spring:
  application:
    name: sukiverse
  profiles:
    active: local
  jpa:
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
  cache:
    type: redis
  flyway:
    enabled: true
    locations: classpath:db/migration
    # 타임스탬프 형식으로 버전을 관리하기 때문에 먼저 만든 마이그레이션이 나중에 머지되는 일을 방지
    out-of-order: true
